{-# LANGUAGE OverloadedStrings #-}

-- | Scheme code generation backend for CHR VM programs.
--
-- Translates a 'VMProgram' into R7RS Scheme source code that uses the
-- YCHR Scheme runtime libraries (@(ychr var)@, @(ychr store)@,
-- @(ychr history)@, @(ychr reactivation)@).
--
-- Control flow ('Return', 'Break', 'Continue') is implemented via
-- @call\/cc@ escape continuations.  Internal names use a @%@ prefix
-- to avoid collisions with user-defined identifiers.
module YCHR.Backend.Scheme
  ( generateScheme,
    compileSymbol,
    isValidSchemeIdentifier,
  )
where

import Data.Char (isAlpha, isAlphaNum)
import Data.Map.Strict qualified as Map
import Data.Set (Set)
import Data.Set qualified as Set
import Data.Text (Text)
import Data.Text qualified as T
import YCHR.Compile (tellProcName)
import YCHR.SExpr (SExpr (..), printSExpr)
import YCHR.Types qualified as Types
import YCHR.VM.SExpr (VMProgram (..))
import YCHR.VM.Types

-- ---------------------------------------------------------------------------
-- Public API
-- ---------------------------------------------------------------------------

-- | Generate Scheme source code from a VM program, wrapped in an R6RS
-- @(library ...)@ form.  Only the @tell_*@ procedures for exported
-- constraints are listed in the @(export ...)@ clause.
--
-- The library name components are given as a list of 'Text' values,
-- e.g. @["ychr", "generated", "order"]@ produces @(ychr generated order)@.
generateScheme :: [Text] -> VMProgram -> Text
generateScheme libName vmp =
  let procs = vmp.program.procedures
      unknownHC = collectUnknownHostCalls procs
      stubs = map compileHostCallStub (Set.toList unknownHC)
   in T.unlines $
        [ ";; Generated by YCHR",
          "(library " <> renderSExpr (SList (map SAtom libName)),
          "  " <> renderSExpr (exportClause vmp),
          "  " <> renderSExpr importClause,
          "",
          preambleText vmp.program.numTypes
        ]
          ++ map renderSExpr stubs
          ++ map renderSExpr (concatMap compileProcedure procs)
          ++ [") ;; end library"]

-- ---------------------------------------------------------------------------
-- Library wrapper
-- ---------------------------------------------------------------------------

-- | Build the @(export ...)@ clause containing only the @tell_*@ procedures
-- for constraints that actually have a generated @tell_*@ procedure,
-- plus @%init!@.
exportClause :: VMProgram -> SExpr
exportClause vmp =
  let procNames = Set.fromList [n.unName | p <- vmp.program.procedures, let n = p.name]
      tellNames =
        [ mangleName tn
        | Types.QualifiedIdentifier m n a <- Set.toList vmp.exportedSet,
          let tn = tellProcName (Types.Qualified m n) a,
          Set.member tn.unName procNames
        ]
   in SList (SAtom "export" : SAtom "%init!" : map SAtom tellNames)

-- | Import clause for the runtime.
importClause :: SExpr
importClause =
  SList
    [ SAtom "import",
      SList [SAtom "rnrs"],
      SList [SAtom "ychr", SAtom "runtime"]
    ]

-- ---------------------------------------------------------------------------
-- Preamble (runtime helpers as raw text)
-- ---------------------------------------------------------------------------

-- | Generate the program-specific preamble: @%init!@ creates a session.
preambleText :: Int -> Text
preambleText numTypes =
  "(define (%init!) (%make-session " <> T.pack (show numTypes) <> "))"

-- ---------------------------------------------------------------------------
-- Rendering
-- ---------------------------------------------------------------------------

renderSExpr :: SExpr -> Text
renderSExpr = printSExpr

-- ---------------------------------------------------------------------------
-- Procedure compilation
-- ---------------------------------------------------------------------------

compileProcedure :: Procedure -> [SExpr]
compileProcedure proc =
  [ SList
      ( SAtom "define"
          : SList
            ( SAtom (mangleName proc.name)
                : SAtom "%s"
                : map
                  (SAtom . mangleName)
                  proc.params
            )
          : [wrapReturn (compileStmts proc.body)]
      )
  ]

-- | Wrap a procedure body in a call/cc for %return.
wrapReturn :: SExpr -> SExpr
wrapReturn body =
  SList
    [ SAtom "call/cc",
      SList [SAtom "lambda", SList [SAtom "%return"], body, SAtom "#f"]
    ]

-- ---------------------------------------------------------------------------
-- Statement compilation
-- ---------------------------------------------------------------------------

-- | Compile a list of statements into a single SExpr.
-- Let statements thread as nested let bindings wrapping the rest.
compileStmts :: [Stmt] -> SExpr
compileStmts [] = SAtom "#f"
compileStmts [s] = compileStmtTail s []
compileStmts (s : rest) = compileStmtTail s rest

-- | Compile a statement with its continuation (remaining statements).
-- Let creates a nested let wrapping the rest; other statements emit
-- themselves followed by the rest in a begin.
compileStmtTail :: Stmt -> [Stmt] -> SExpr
compileStmtTail (LetVal n e) rest =
  SList
    [ SAtom "let",
      SList [SList [SAtom (mangleName n), compileValExpr e]],
      compileStmts rest
    ]
compileStmtTail (LetId n e) rest =
  SList
    [ SAtom "let",
      SList [SList [SAtom (mangleName n), compileIdExpr e]],
      compileStmts rest
    ]
compileStmtTail s [] = compileStmt s
compileStmtTail s rest =
  SList (SAtom "begin" : compileStmt s : [compileStmts rest])

-- | Compile a single statement (no continuation context).
compileStmt :: Stmt -> SExpr
compileStmt (LetVal n e) =
  SList [SAtom "let", SList [SList [SAtom (mangleName n), compileValExpr e]], SAtom "#f"]
compileStmt (LetId n e) =
  SList [SAtom "let", SList [SList [SAtom (mangleName n), compileIdExpr e]], SAtom "#f"]
compileStmt (AssignVal n e) =
  SList [SAtom "set!", SAtom (mangleName n), compileValExpr e]
compileStmt (AssignId n e) =
  SList [SAtom "set!", SAtom (mangleName n), compileIdExpr e]
compileStmt (If cond thenBranch elseBranch) =
  SList
    [ SAtom "if",
      compileBoolExpr cond,
      compileBody thenBranch,
      compileBody elseBranch
    ]
compileStmt (Foreach lbl (ConstraintType ct) sv conds body) =
  compileForeach lbl ct sv conds body
compileStmt (Continue (Label lbl)) =
  SList [SAtom (continueName lbl), SAtom "#f"]
compileStmt (Break (Label lbl)) =
  SList [SAtom (breakName lbl), SAtom "#f"]
compileStmt (Return e) =
  SList [SAtom "%return", compileValExpr e]
compileStmt (ExprStmt e) =
  compileValExpr e
compileStmt (BoolExprStmt e) =
  compileBoolExpr e
compileStmt (Store e) =
  SList [SAtom "store-constraint", SAtom "%s", compileIdExpr e]
compileStmt (Kill e) =
  SList [SAtom "kill-constraint", compileIdExpr e]
compileStmt (AddHistory (RuleId rid) es) =
  SList
    [ SAtom "add-history!",
      SAtom "%s",
      SInt rid,
      SList
        ( SAtom "list"
            : map (\e -> SList [SAtom "constraint-id", compileIdExpr e]) es
        )
    ]
compileStmt (PushFrame _) =
  SList [SAtom "values"]
compileStmt (DrainReactivationQueue (Name sv) body) =
  SList
    [ SAtom "drain-queue!",
      SAtom "%s",
      SList
        [ SAtom "lambda",
          SList [SAtom sv],
          SList
            [ SAtom "when",
              SList [SAtom "alive-constraint?", SAtom sv],
              compileBody body
            ]
        ]
    ]

-- | Compile a statement list as a body (begin-wrapped if multiple).
compileBody :: [Stmt] -> SExpr
compileBody [] = SAtom "#f"
compileBody [s] = compileStmt s
compileBody stmts = compileStmts stmts

-- ---------------------------------------------------------------------------
-- Foreach compilation
-- ---------------------------------------------------------------------------

compileForeach :: Label -> Int -> Name -> [(ArgIndex, ValExpr)] -> [Stmt] -> SExpr
compileForeach (Label lbl) ct (Name sv) conds body =
  SList
    [ SAtom "call/cc",
      SList
        [ SAtom "lambda",
          SList [SAtom (breakName lbl)],
          SList
            [ SAtom "let-values",
              SList
                [ SList
                    [ SList [SAtom "%vec", SAtom "%count"],
                      SList [SAtom "store-snapshot", SAtom "%s", SInt ct]
                    ]
                ],
              SList
                [ SAtom "let",
                  SAtom (foreachName lbl),
                  SList [SList [SAtom "%i", SInt 0]],
                  SList
                    [ SAtom "when",
                      SList [SAtom "<", SAtom "%i", SAtom "%count"],
                      SList
                        [ SAtom "let",
                          SList
                            [ SList
                                [ SAtom sv,
                                  SList
                                    [ SAtom "vector-ref",
                                      SAtom "%vec",
                                      SAtom "%i"
                                    ]
                                ]
                            ],
                          foreachInner lbl sv conds body
                        ],
                      SList [SAtom (foreachName lbl), SList [SAtom "+", SAtom "%i", SInt 1]]
                    ]
                ]
            ]
        ]
    ]

foreachInner :: Text -> Text -> [(ArgIndex, ValExpr)] -> [Stmt] -> SExpr
foreachInner lbl sv conds body =
  let aliveCheck = SList [SAtom "suspension-alive?", SAtom sv]
      condChecks = map compileCondition conds
      allChecks = aliveCheck : condChecks
      guard = case allChecks of
        [c] -> c
        cs -> SList (SAtom "and" : cs)
      innerBody =
        SList
          [ SAtom "call/cc",
            SList
              [ SAtom "lambda",
                SList [SAtom (continueName lbl)],
                compileBody body
              ]
          ]
   in SList [SAtom "when", guard, innerBody]
  where
    compileCondition (ArgIndex i, e) =
      SList
        [ SAtom "equal?/chr",
          SList [SAtom "constraint-arg", SAtom sv, SInt i],
          compileValExpr e
        ]

-- ---------------------------------------------------------------------------
-- Expression compilation
-- ---------------------------------------------------------------------------

compileValExpr :: ValExpr -> SExpr
compileValExpr (Var n) = SAtom (mangleName n)
compileValExpr (Lit l) = compileLiteral l
compileValExpr (CallExpr n args) =
  SList (SAtom (mangleName n) : SAtom "%s" : map compileCallArg args)
compileValExpr (HostCall n args) =
  compileHostCall n args
compileValExpr (EvalDeep e) =
  compileEvalDeep e
compileValExpr NewVar =
  SList [SAtom "make-var", SAtom "%s"]
compileValExpr (MakeTerm (Name f) args) =
  SList
    [ SAtom "make-term",
      compileSymbol f,
      SList (SAtom "vector" : map compileValExpr args)
    ]
compileValExpr (GetArg e i) =
  SList [SAtom "get-arg", compileValExpr e, SInt i]
compileValExpr (FieldArg e (ArgIndex i)) =
  SList [SAtom "constraint-arg", compileIdExpr e, SInt i]
compileValExpr (FieldType e) =
  SList [SAtom "constraint-type", compileIdExpr e]

-- | Compile a 'BoolExpr' to a Scheme boolean expression. Scheme is
-- dynamically typed, so 'BFromVal' is identical to compiling the
-- wrapped 'ValExpr' — the runtime accepts whatever truthy value the
-- underlying value produces.
compileBoolExpr :: BoolExpr -> SExpr
compileBoolExpr (BLit True) = SAtom "#t"
compileBoolExpr (BLit False) = SAtom "#f"
compileBoolExpr (BNot e) = SList [SAtom "not", compileBoolExpr e]
compileBoolExpr (BAnd a b) = SList [SAtom "and", compileBoolExpr a, compileBoolExpr b]
compileBoolExpr (BOr a b) = SList [SAtom "or", compileBoolExpr a, compileBoolExpr b]
compileBoolExpr (BMatchTerm e (Name f) arity) =
  SList [SAtom "match-term", compileValExpr e, compileSymbol f, SInt arity]
compileBoolExpr (BEqual a b) =
  SList [SAtom "equal?/chr", compileValExpr a, compileValExpr b]
compileBoolExpr (BIdEqual a b) =
  SList [SAtom "id-equal?", compileIdExpr a, compileIdExpr b]
compileBoolExpr (BAlive e) =
  SList [SAtom "alive-constraint?", compileIdExpr e]
compileBoolExpr (BIsConstraintType e (ConstraintType ct)) =
  SList [SAtom "is-constraint-type?", compileIdExpr e, SInt ct]
compileBoolExpr (BNotInHistory (RuleId rid) es) =
  SList
    [ SAtom "not-in-history?",
      SAtom "%s",
      SInt rid,
      SList
        ( SAtom "list"
            : map (\e -> SList [SAtom "constraint-id", compileIdExpr e]) es
        )
    ]
compileBoolExpr (BUnify a b) =
  SList [SAtom "%unify", SAtom "%s", compileValExpr a, compileValExpr b]
compileBoolExpr (BFromVal e) = compileValExpr e
compileBoolExpr (BEvalDeep e) = compileBoolEvalDeep e

compileIdExpr :: IdExpr -> SExpr
compileIdExpr (IdVar n) = SAtom (mangleName n)
compileIdExpr (CreateConstraint (ConstraintType ct) args) =
  SList
    [ SAtom "create-constraint",
      SAtom "%s",
      SInt ct,
      SList (SAtom "vector" : map compileValExpr args)
    ]

compileCallArg :: CallArg -> SExpr
compileCallArg (AVal e) = compileValExpr e
compileCallArg (AId e) = compileIdExpr e

-- ---------------------------------------------------------------------------
-- Literal compilation
-- ---------------------------------------------------------------------------

compileLiteral :: Literal -> SExpr
compileLiteral (IntLit n) = SInt n
compileLiteral (FloatLit n) = SFloat n
compileLiteral (AtomLit s) = compileSymbol s
compileLiteral (TextLit s) = SString s
compileLiteral (BoolLit True) = SAtom "#t"
compileLiteral (BoolLit False) = SAtom "#f"
compileLiteral WildcardLit = SAtom "*wildcard*"

-- | Compile a text to a Scheme symbol expression.
-- Uses @(quote sym)@ for valid identifiers, @(string->symbol "...")@ otherwise.
compileSymbol :: Text -> SExpr
compileSymbol s
  | isValidSchemeIdentifier s = SList [SAtom "quote", SAtom s]
  | otherwise = SList [SAtom "string->symbol", SString s]

-- ---------------------------------------------------------------------------
-- Host calls
-- ---------------------------------------------------------------------------

-- | Known host call name mapping.
hostCallMap :: Map.Map Text Text
hostCallMap =
  Map.fromList
    [ ("div", "%idiv"),
      ("mod", "%imod"),
      ("rem", "mod0"),
      ("=<", "<="),
      ("==", "equal?/chr"),
      ("float", "flonum?"),
      ("int_to_float", "%int-to-float"),
      ("float_to_int", "%float-to-int"),
      ("write", "display"),
      ("print", "%print"),
      ("string_concat", "string-append"),
      ("string_length", "string-length"),
      ("string_upper", "string-upcase"),
      ("string_lower", "string-downcase"),
      ("__chr_error", "%chr-error"),
      ("integer", "integer?"),
      ("atom", "symbol?"),
      ("boolean", "boolean?"),
      ("string", "string?"),
      ("var", "var?"),
      ("nonvar", "%nonvar?"),
      ("unifiable", "%unifiable?"),
      ("ground", "%ground?"),
      ("term_variables", "%term-variables"),
      ("compound_to_list", "%compound-to-list"),
      ("list_to_compound", "%list-to-compound"),
      ("read_term_from_string", "%read-term-from-string"),
      ("copy_term", "%copy-term")
    ]

-- | Host calls that need the session threaded as their first argument.
sessionHostCalls :: Set.Set Text
sessionHostCalls = Set.fromList ["copy_term"]

-- | Compile a host call. Arguments are dereferenced before calling.
-- Calls listed in 'sessionHostCalls' get the session @%s@ threaded as
-- their first argument (before the user-visible arguments).
compileHostCall :: Name -> [ValExpr] -> SExpr
compileHostCall = compileHostCallWith compileValExpr

-- | Worker for 'compileHostCall' parameterized by how arguments are
-- compiled. 'compileEvalDeep' reuses this with itself as the inner
-- compiler so deep-deref propagates into host-call arguments.
compileHostCallWith :: (ValExpr -> SExpr) -> Name -> [ValExpr] -> SExpr
compileHostCallWith compile (Name n) args =
  let fn = Map.findWithDefault n n hostCallMap
      derefedArgs = map (\a -> SList [SAtom "deref", compile a]) args
      allArgs
        | Set.member n sessionHostCalls = SAtom "%s" : derefedArgs
        | otherwise = derefedArgs
   in SList (SAtom fn : allArgs)

-- | Compile an EvalDeep expression. Like the standard expression
-- compiler, but Var references are dereferenced (following binding
-- chains) and the transformation propagates recursively into
-- sub-expressions ('call-expr' arguments, 'make-term' arguments,
-- 'host-call' arguments).
compileEvalDeep :: ValExpr -> SExpr
compileEvalDeep (Lit l) = compileLiteral l
compileEvalDeep (Var n) = SList [SAtom "deref", SAtom (mangleName n)]
compileEvalDeep (HostCall n args) = compileHostCallWith compileEvalDeep n args
compileEvalDeep (CallExpr n args) =
  SList (SAtom (mangleName n) : SAtom "%s" : map compileCallArgDeep args)
compileEvalDeep (MakeTerm (Name f) args) =
  SList
    [ SAtom "make-term",
      compileSymbol f,
      SList (SAtom "vector" : map compileEvalDeep args)
    ]
compileEvalDeep e = compileValExpr e -- GetArg, FieldArg, FieldType, NewVar

compileCallArgDeep :: CallArg -> SExpr
compileCallArgDeep (AVal e) = compileEvalDeep e
compileCallArgDeep (AId e) = compileIdExpr e

-- | Like 'compileBoolExpr', but propagates deep-deref into 'ValExpr'
-- and 'IdExpr' payloads. Mirrors 'compileEvalDeep' for booleans.
compileBoolEvalDeep :: BoolExpr -> SExpr
compileBoolEvalDeep (BNot e) = SList [SAtom "not", compileBoolEvalDeep e]
compileBoolEvalDeep (BAnd a b) =
  SList [SAtom "and", compileBoolEvalDeep a, compileBoolEvalDeep b]
compileBoolEvalDeep (BOr a b) =
  SList [SAtom "or", compileBoolEvalDeep a, compileBoolEvalDeep b]
compileBoolEvalDeep (BMatchTerm e (Name f) arity) =
  SList [SAtom "match-term", compileEvalDeep e, compileSymbol f, SInt arity]
compileBoolEvalDeep (BEqual a b) =
  SList [SAtom "equal?/chr", compileEvalDeep a, compileEvalDeep b]
compileBoolEvalDeep (BUnify a b) =
  SList [SAtom "%unify", SAtom "%s", compileEvalDeep a, compileEvalDeep b]
compileBoolEvalDeep (BFromVal e) = compileEvalDeep e
compileBoolEvalDeep (BEvalDeep e) = compileBoolEvalDeep e
compileBoolEvalDeep e = compileBoolExpr e

-- ---------------------------------------------------------------------------
-- Unknown host call stubs
-- ---------------------------------------------------------------------------

-- | Collect all host call names used in the program that are NOT in the
-- known mapping and NOT standard Scheme operators.  These need stubs
-- so that R6RS doesn't reject unbound identifiers at compile time.
collectUnknownHostCalls :: [Procedure] -> Set Text
collectUnknownHostCalls procs =
  let allHC = foldMap (foldMap collectStmtHC . (.body)) procs
      known = Set.fromList $ Map.keys hostCallMap ++ Map.elems hostCallMap ++ schemeBuiltins
   in Set.difference allHC known

-- | Scheme builtins that don't need stubs.
schemeBuiltins :: [Text]
schemeBuiltins =
  [ "+",
    "-",
    "*",
    "/",
    "div",
    "mod",
    "mod0",
    "<",
    ">",
    ">=",
    "<=",
    "eqv?",
    "equal?",
    "display",
    "newline",
    "string-append",
    "string-length",
    "string-upcase",
    "string-downcase",
    "integer?",
    "symbol?",
    "boolean?",
    "string?",
    "not"
  ]

-- | Collect host call names from a statement.
collectStmtHC :: Stmt -> Set Text
collectStmtHC (LetVal _ e) = collectValHC e
collectStmtHC (LetId _ e) = collectIdHC e
collectStmtHC (AssignVal _ e) = collectValHC e
collectStmtHC (AssignId _ e) = collectIdHC e
collectStmtHC (If c ts es) =
  collectBoolHC c
    <> foldMap collectStmtHC ts
    <> foldMap collectStmtHC es
collectStmtHC (Foreach _ _ _ conds body) =
  foldMap (collectValHC . snd) conds
    <> foldMap collectStmtHC body
collectStmtHC (Return e) = collectValHC e
collectStmtHC (ExprStmt e) = collectValHC e
collectStmtHC (BoolExprStmt e) = collectBoolHC e
collectStmtHC (Store e) = collectIdHC e
collectStmtHC (Kill e) = collectIdHC e
collectStmtHC (AddHistory _ es) = foldMap collectIdHC es
collectStmtHC (DrainReactivationQueue _ body) = foldMap collectStmtHC body
collectStmtHC _ = Set.empty

-- | Collect host call names from a value expression.
collectValHC :: ValExpr -> Set Text
collectValHC (HostCall (Name n) args) = Set.singleton n <> foldMap collectValHC args
collectValHC (EvalDeep e) = collectValHC e
collectValHC (CallExpr _ args) = foldMap collectArgHC args
collectValHC (MakeTerm _ args) = foldMap collectValHC args
collectValHC (GetArg e _) = collectValHC e
collectValHC (FieldArg e _) = collectIdHC e
collectValHC (FieldType e) = collectIdHC e
collectValHC _ = Set.empty

-- | Collect host call names from a boolean expression.
collectBoolHC :: BoolExpr -> Set Text
collectBoolHC (BNot e) = collectBoolHC e
collectBoolHC (BAnd a b) = collectBoolHC a <> collectBoolHC b
collectBoolHC (BOr a b) = collectBoolHC a <> collectBoolHC b
collectBoolHC (BMatchTerm e _ _) = collectValHC e
collectBoolHC (BEqual a b) = collectValHC a <> collectValHC b
collectBoolHC (BIdEqual a b) = collectIdHC a <> collectIdHC b
collectBoolHC (BAlive e) = collectIdHC e
collectBoolHC (BIsConstraintType e _) = collectIdHC e
collectBoolHC (BNotInHistory _ es) = foldMap collectIdHC es
collectBoolHC (BUnify a b) = collectValHC a <> collectValHC b
collectBoolHC (BFromVal e) = collectValHC e
collectBoolHC (BEvalDeep e) = collectBoolHC e
collectBoolHC (BLit _) = Set.empty

collectIdHC :: IdExpr -> Set Text
collectIdHC (IdVar _) = Set.empty
collectIdHC (CreateConstraint _ args) = foldMap collectValHC args

collectArgHC :: CallArg -> Set Text
collectArgHC (AVal e) = collectValHC e
collectArgHC (AId e) = collectIdHC e

-- | Generate a stub for an unknown host call. The stub accepts any number
-- of arguments and raises an error.
compileHostCallStub :: Text -> SExpr
compileHostCallStub name =
  SList
    [ SAtom "define",
      SList [SAtom name, SAtom ".", SAtom "args"],
      SList [SAtom "error", SList [SAtom "quote", SAtom name], SString "not implemented"]
    ]

-- ---------------------------------------------------------------------------
-- Name mangling
-- ---------------------------------------------------------------------------

mangleName :: Name -> Text
mangleName (Name n) = n

-- | Continuation name for a foreach break.
breakName :: Text -> Text
breakName lbl = "%break-" <> lbl

-- | Continuation name for a foreach continue.
continueName :: Text -> Text
continueName lbl = "%continue-" <> lbl

-- | Named let for foreach loop.
foreachName :: Text -> Text
foreachName lbl = "%foreach-" <> lbl

-- | Check whether a text is a valid R7RS Scheme identifier.
-- Conservative: allows alphanumeric, underscore, hyphen, and common
-- Scheme "extended" identifier characters.
isValidSchemeIdentifier :: Text -> Bool
isValidSchemeIdentifier t = case T.uncons t of
  Nothing -> False
  Just (c, rest) ->
    isSchemeInitial c && T.all isSchemeSubsequent rest
  where
    isSchemeInitial c = isAlpha c || c `elem` ("!$%&*/:<=>?^_~" :: [Char])
    isSchemeSubsequent c = isSchemeInitial c || isAlphaNum c || c `elem` ("+-.@" :: [Char])
