{-# LANGUAGE OverloadedStrings #-}

-- | Scheme code generation backend for CHR VM programs.
--
-- Translates a 'VMProgram' into R7RS Scheme source code that uses the
-- YCHR Scheme runtime libraries (@(ychr var)@, @(ychr store)@,
-- @(ychr history)@, @(ychr reactivation)@).
--
-- Control flow ('Return', 'Break', 'Continue') is implemented via
-- @call\/cc@ escape continuations.  Internal names use a @%@ prefix
-- to avoid collisions with user-defined identifiers.
module YCHR.Backend.Scheme
  ( generateScheme,
  )
where

import Data.Char (isAlpha, isAlphaNum)
import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as T
import YCHR.SExpr (SExpr (..), printSExpr)
import YCHR.VM.SExpr (VMProgram (..))
import YCHR.VM.Types

-- ---------------------------------------------------------------------------
-- Public API
-- ---------------------------------------------------------------------------

-- | Generate Scheme source code from a VM program.
generateScheme :: VMProgram -> Text
generateScheme vmp =
  T.unlines $
    [";; Generated by YCHR"]
      ++ [renderSExpr imports]
      ++ [""]
      ++ map renderSExpr (preambleFor vmp.program.numTypes)
      ++ [""]
      ++ map renderSExpr (concatMap compileProcedure vmp.program.procedures)

-- ---------------------------------------------------------------------------
-- Imports
-- ---------------------------------------------------------------------------

imports :: SExpr
imports =
  SList
    [ SAtom "import",
      SList [SAtom "scheme", SAtom "base"],
      SList [SAtom "ychr", SAtom "var"],
      SList [SAtom "ychr", SAtom "store"],
      SList [SAtom "ychr", SAtom "history"],
      SList [SAtom "ychr", SAtom "reactivation"]
    ]

-- ---------------------------------------------------------------------------
-- Preamble (runtime helpers)
-- ---------------------------------------------------------------------------

-- | Build the preamble with the correct numTypes.
preambleFor :: Int -> [SExpr]
preambleFor n =
  [ -- %init!
    SList
      [ SAtom "define",
        SList [SAtom "%init!"],
        SList [SAtom "reset-var-counter!"],
        SList [SAtom "init-store!", SInt n],
        SList [SAtom "init-history!"],
        SList [SAtom "init-react-queue!"]
      ],
    -- %unify
    SList
      [ SAtom "define",
        SList [SAtom "%unify", SAtom "v1", SAtom "v2"],
        SList
          [ SAtom "let-values",
            SList [SList [SList [SAtom "ok", SAtom "observers"], SList [SAtom "unify", SAtom "v1", SAtom "v2"]]],
            SList [SAtom "enqueue!", SAtom "observers"],
            SAtom "ok"
          ]
      ],
    -- %ground?
    SList
      [ SAtom "define",
        SList [SAtom "%ground?", SAtom "v"],
        SList
          [ SAtom "let",
            SList [SList [SAtom "d", SList [SAtom "deref", SAtom "v"]]],
            SList
              [ SAtom "cond",
                SList [SList [SAtom "var?", SAtom "d"], SAtom "#f"],
                SList
                  [ SList [SAtom "term?", SAtom "d"],
                    SList
                      [ SAtom "let",
                        SList [SList [SAtom "a", SList [SAtom "term-args", SAtom "d"]]],
                        SList
                          [ SAtom "let",
                            SAtom "%loop",
                            SList [SList [SAtom "i", SInt 0]],
                            SList
                              [ SAtom "if",
                                SList [SAtom ">=", SAtom "i", SList [SAtom "vector-length", SAtom "a"]],
                                SAtom "#t",
                                SList
                                  [ SAtom "and",
                                    SList [SAtom "%ground?", SList [SAtom "vector-ref", SAtom "a", SAtom "i"]],
                                    SList [SAtom "%loop", SList [SAtom "+", SAtom "i", SInt 1]]
                                  ]
                              ]
                          ]
                      ]
                  ],
                SList [SAtom "else", SAtom "#t"]
              ]
          ]
      ],
    -- %nonvar?
    SList
      [ SAtom "define",
        SList [SAtom "%nonvar?", SAtom "v"],
        SList [SAtom "not", SList [SAtom "var?", SAtom "v"]]
      ],
    -- %chr-error
    SList
      [ SAtom "define",
        SList [SAtom "%chr-error"],
        SList [SAtom "error", SString "CHR runtime error: no matching equation"]
      ]
  ]

-- ---------------------------------------------------------------------------
-- Rendering
-- ---------------------------------------------------------------------------

renderSExpr :: SExpr -> Text
renderSExpr = printSExpr

-- ---------------------------------------------------------------------------
-- Procedure compilation
-- ---------------------------------------------------------------------------

compileProcedure :: Procedure -> [SExpr]
compileProcedure proc =
  [ SList
      ( SAtom "define"
          : SList (SAtom (mangleName proc.name) : map (SAtom . mangleName) proc.params)
          : [wrapReturn (compileStmts proc.body)]
      )
  ]

-- | Wrap a procedure body in a call/cc for %return.
wrapReturn :: SExpr -> SExpr
wrapReturn body =
  SList
    [ SAtom "call/cc",
      SList [SAtom "lambda", SList [SAtom "%return"], body, SAtom "#f"]
    ]

-- ---------------------------------------------------------------------------
-- Statement compilation
-- ---------------------------------------------------------------------------

-- | Compile a list of statements into a single SExpr.
-- Let statements thread as nested let bindings wrapping the rest.
compileStmts :: [Stmt] -> SExpr
compileStmts [] = SList [SAtom "begin"]
compileStmts [s] = compileStmtTail s []
compileStmts (s : rest) = compileStmtTail s rest

-- | Compile a statement with its continuation (remaining statements).
-- Let creates a nested let wrapping the rest; other statements emit
-- themselves followed by the rest in a begin.
compileStmtTail :: Stmt -> [Stmt] -> SExpr
compileStmtTail (Let n e) rest =
  SList
    [ SAtom "let",
      SList [SList [SAtom (mangleName n), compileExpr e]],
      compileStmts rest
    ]
compileStmtTail s [] = compileStmt s
compileStmtTail s rest =
  SList (SAtom "begin" : compileStmt s : [compileStmts rest])

-- | Compile a single statement (no continuation context).
compileStmt :: Stmt -> SExpr
compileStmt (Let n e) =
  -- Standalone let (no continuation) — bind to nothing useful
  SList [SAtom "let", SList [SList [SAtom (mangleName n), compileExpr e]], SList [SAtom "begin"]]
compileStmt (Assign n e) =
  SList [SAtom "set!", SAtom (mangleName n), compileExpr e]
compileStmt (If cond thenBranch elseBranch) =
  SList
    [ SAtom "if",
      compileExpr cond,
      compileBody thenBranch,
      compileBody elseBranch
    ]
compileStmt (Foreach lbl (ConstraintType ct) sv conds body) =
  compileForeach lbl ct sv conds body
compileStmt (Continue (Label lbl)) =
  SList [SAtom (continueName lbl), SAtom "#f"]
compileStmt (Break (Label lbl)) =
  SList [SAtom (breakName lbl), SAtom "#f"]
compileStmt (Return e) =
  SList [SAtom "%return", compileExpr e]
compileStmt (ExprStmt e) =
  compileExpr e
compileStmt (Store e) =
  SList [SAtom "store-constraint", compileExpr e]
compileStmt (Kill e) =
  SList [SAtom "kill-constraint", compileExpr e]
compileStmt (AddHistory (RuleName rn) es) =
  SList
    [ SAtom "add-history!",
      SList [SAtom "quote", SAtom rn],
      SList (SAtom "list" : map (\e -> SList [SAtom "constraint-id", compileExpr e]) es)
    ]
compileStmt (DrainReactivationQueue (Name sv) body) =
  SList
    [ SAtom "drain-queue!",
      SList
        [ SAtom "lambda",
          SList [SAtom sv],
          SList
            [ SAtom "when",
              SList [SAtom "alive-constraint?", SAtom sv],
              compileBody body
            ]
        ]
    ]

-- | Compile a statement list as a body (begin-wrapped if multiple).
compileBody :: [Stmt] -> SExpr
compileBody [] = SList [SAtom "begin"]
compileBody [s] = compileStmt s
compileBody stmts = compileStmts stmts

-- ---------------------------------------------------------------------------
-- Foreach compilation
-- ---------------------------------------------------------------------------

compileForeach :: Label -> Int -> Name -> [(ArgIndex, Expr)] -> [Stmt] -> SExpr
compileForeach (Label lbl) ct (Name sv) conds body =
  SList
    [ SAtom "call/cc",
      SList
        [ SAtom "lambda",
          SList [SAtom (breakName lbl)],
          SList
            [ SAtom "let-values",
              SList
                [ SList
                    [ SList [SAtom "%vec", SAtom "%count"],
                      SList [SAtom "store-snapshot", SInt ct]
                    ]
                ],
              SList
                [ SAtom "let",
                  SAtom (foreachName lbl),
                  SList [SList [SAtom "%i", SInt 0]],
                  SList
                    [ SAtom "when",
                      SList [SAtom "<", SAtom "%i", SAtom "%count"],
                      SList
                        [ SAtom "let",
                          SList [SList [SAtom sv, SList [SAtom "vector-ref", SAtom "%vec", SAtom "%i"]]],
                          foreachInner lbl sv conds body
                        ],
                      SList [SAtom (foreachName lbl), SList [SAtom "+", SAtom "%i", SInt 1]]
                    ]
                ]
            ]
        ]
    ]

foreachInner :: Text -> Text -> [(ArgIndex, Expr)] -> [Stmt] -> SExpr
foreachInner lbl sv conds body =
  let aliveCheck = SList [SAtom "suspension-alive?", SAtom sv]
      condChecks = map compileCondition conds
      allChecks = aliveCheck : condChecks
      guard = case allChecks of
        [c] -> c
        cs -> SList (SAtom "and" : cs)
      innerBody =
        SList
          [ SAtom "call/cc",
            SList
              [ SAtom "lambda",
                SList [SAtom (continueName lbl)],
                compileBody body
              ]
          ]
   in SList [SAtom "when", guard, innerBody]
  where
    compileCondition (ArgIndex i, e) =
      SList [SAtom "equal?/chr", SList [SAtom "constraint-arg", SAtom sv, SInt i], compileExpr e]

-- ---------------------------------------------------------------------------
-- Expression compilation
-- ---------------------------------------------------------------------------

compileExpr :: Expr -> SExpr
compileExpr (Var n) = SAtom (mangleName n)
compileExpr (Lit l) = compileLiteral l
compileExpr (CallExpr n args) =
  SList (SAtom (mangleName n) : map compileExpr args)
compileExpr (HostCall n args) =
  compileHostCall n args
compileExpr (HostEval e) =
  compileHostEval e
compileExpr (Not e) =
  SList [SAtom "not", compileExpr e]
compileExpr (And a b) =
  SList [SAtom "and", compileExpr a, compileExpr b]
compileExpr (Or a b) =
  SList [SAtom "or", compileExpr a, compileExpr b]
compileExpr NewVar =
  SList [SAtom "make-var"]
compileExpr (MakeTerm (Name f) args) =
  SList
    [ SAtom "make-term",
      compileSymbol f,
      SList (SAtom "vector" : map compileExpr args)
    ]
compileExpr (MatchTerm e (Name f) arity) =
  SList [SAtom "match-term", compileExpr e, compileSymbol f, SInt arity]
compileExpr (GetArg e i) =
  SList [SAtom "get-arg", compileExpr e, SInt i]
compileExpr (CreateConstraint (ConstraintType ct) args) =
  SList
    [ SAtom "create-constraint",
      SInt ct,
      SList (SAtom "vector" : map compileExpr args)
    ]
compileExpr (Alive e) =
  SList [SAtom "alive-constraint?", compileExpr e]
compileExpr (IdEqual a b) =
  SList [SAtom "id-equal?", compileExpr a, compileExpr b]
compileExpr (IsConstraintType e (ConstraintType ct)) =
  SList [SAtom "is-constraint-type?", compileExpr e, SInt ct]
compileExpr (NotInHistory (RuleName rn) es) =
  SList
    [ SAtom "not-in-history?",
      SList [SAtom "quote", SAtom rn],
      SList (SAtom "list" : map (\e -> SList [SAtom "constraint-id", compileExpr e]) es)
    ]
compileExpr (Unify a b) =
  SList [SAtom "%unify", compileExpr a, compileExpr b]
compileExpr (Equal a b) =
  SList [SAtom "equal?/chr", compileExpr a, compileExpr b]
compileExpr (FieldGet e FieldId) =
  compileExpr e -- suspension IS the identifier
compileExpr (FieldGet e (FieldArg (ArgIndex i))) =
  SList [SAtom "constraint-arg", compileExpr e, SInt i]
compileExpr (FieldGet e FieldType) =
  SList [SAtom "constraint-type", compileExpr e]

-- ---------------------------------------------------------------------------
-- Literal compilation
-- ---------------------------------------------------------------------------

compileLiteral :: Literal -> SExpr
compileLiteral (IntLit n) = SInt n
compileLiteral (AtomLit s) = compileSymbol s
compileLiteral (TextLit s) = SString s
compileLiteral (BoolLit True) = SAtom "#t"
compileLiteral (BoolLit False) = SAtom "#f"
compileLiteral WildcardLit = SAtom "*wildcard*"

-- | Compile a text to a Scheme symbol expression.
-- Uses @(quote sym)@ for valid identifiers, @(string->symbol "...")@ otherwise.
compileSymbol :: Text -> SExpr
compileSymbol s
  | isValidSchemeIdentifier s = SList [SAtom "quote", SAtom s]
  | otherwise = SList [SAtom "string->symbol", SString s]

-- ---------------------------------------------------------------------------
-- Host calls
-- ---------------------------------------------------------------------------

-- | Known host call name mapping.
hostCallMap :: Map.Map Text Text
hostCallMap =
  Map.fromList
    [ ("div", "quotient"),
      ("mod", "modulo"),
      ("=<", "<="),
      ("==", "eqv?"),
      ("write", "display"),
      ("string_concat", "string-append"),
      ("string_length", "string-length"),
      ("string_upper", "string-upcase"),
      ("string_lower", "string-downcase"),
      ("__chr_error", "%chr-error"),
      ("integer", "integer?"),
      ("atom", "symbol?"),
      ("boolean", "boolean?"),
      ("string", "string?"),
      ("var", "var?"),
      ("nonvar", "%nonvar?"),
      ("ground", "%ground?")
    ]

-- | Compile a host call.  Arguments are dereferenced before calling.
compileHostCall :: Name -> [Expr] -> SExpr
compileHostCall (Name n) args =
  let fn = Map.findWithDefault n n hostCallMap
      derefedArgs = map (\a -> SList [SAtom "deref", compileExpr a]) args
   in SList (SAtom fn : derefedArgs)

-- | Compile a HostEval expression.  MakeTerm is interpreted as function
-- application; Var references are dereferenced.
compileHostEval :: Expr -> SExpr
compileHostEval (Lit l) = compileLiteral l
compileHostEval (Var n) = SList [SAtom "deref", SAtom (mangleName n)]
compileHostEval (MakeTerm (Name f) args) =
  let fn = Map.findWithDefault f f hostCallMap
   in SList (SAtom fn : map compileHostEval args)
compileHostEval (HostCall n args) = compileHostCall n args
compileHostEval (CallExpr n args) =
  SList (SAtom (mangleName n) : map compileHostEval args)
compileHostEval e = compileExpr e -- fallback

-- ---------------------------------------------------------------------------
-- Name mangling
-- ---------------------------------------------------------------------------

mangleName :: Name -> Text
mangleName (Name n) = n

-- | Continuation name for a foreach break.
breakName :: Text -> Text
breakName lbl = "%break-" <> lbl

-- | Continuation name for a foreach continue.
continueName :: Text -> Text
continueName lbl = "%continue-" <> lbl

-- | Named let for foreach loop.
foreachName :: Text -> Text
foreachName lbl = "%foreach-" <> lbl

-- | Check whether a text is a valid R7RS Scheme identifier.
-- Conservative: allows alphanumeric, underscore, hyphen, and common
-- Scheme "extended" identifier characters.
isValidSchemeIdentifier :: Text -> Bool
isValidSchemeIdentifier t = case T.uncons t of
  Nothing -> False
  Just (c, rest) ->
    isSchemeInitial c && T.all isSchemeSubsequent rest
  where
    isSchemeInitial c = isAlpha c || c `elem` ("!$%&*/:<=>?^_~" :: [Char])
    isSchemeSubsequent c = isSchemeInitial c || isAlphaNum c || c `elem` ("+-.@" :: [Char])
